config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: redirect("rooms")

  resources :rooms do
    resources :messages, only: %i[create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  broadcasts_refreshes_to :room

  belongs_to :room
  validates :author, :content, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  broadcasts_refreshes

  has_many :messages, -> { order(created_at: :asc) }, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :set_room
  before_action :set_message, only: :destroy

  def create
    message = @room.messages.build(message_params)
    if message.save
      render turbo_stream: [
        turbo_stream.replace(:message_count, partial: "rooms/message_count", locals: { room: @room }),
        turbo_stream.append(:message_list, partial: "messages/message", locals: { message: message }),
        turbo_stream.replace(:message_form, partial: "messages/form", locals: { message: @room.messages.build(author: message.author) }),
      ]
    else
      render turbo_stream: [
        turbo_stream.replace(:message_form, partial: "messages/form", locals: { message: message }),
      ]
    end
  end

  def destroy
    @message.destroy!
    render turbo_stream: [
      turbo_stream.replace(:message_count, partial: "rooms/message_count", locals: { room: @room }),
      turbo_stream.remove(@message),
    ]
  end

  private

  def message_params
    params.require(:message).permit(
      :author,
      :content
    )
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_message
    @message = @room.messages.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to @room, notice: "Room was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /rooms/1
  def update
    if @room.update(room_params)
      redirect_to @room, notice: "Room was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /rooms/1
  def destroy
    @room.destroy!
    redirect_to rooms_url, notice: "Room was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
  TAILWIND_PALETTE = %w[
    text-red-600
    text-yellow-600
    text-green-600
    text-blue-600
    text-indigo-600
    text-purple-600
    text-pink-600
    text-rose-600
    text-orange-600
    text-amber-600
    text-lime-600
    text-emerald-600
    text-teal-600
    text-cyan-600
    text-sky-600
    text-violet-600
    text-fuchsia-600
  ].freeze

  def message_color_class(message)
    hash = message.author.chars.inject(0) do |hash, char|
      ((hash << 5) - hash) + char.ord
    end
    TAILWIND_PALETTE[hash % TAILWIND_PALETTE.size]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turbochat</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
    <% turbo_refreshes_with method: :morph, scroll: :preserve %>

    <%= content_for :head %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_form.html.erb
<%# locals: (message:) -%>

<%= turbo_frame_tag :message_form do %>
  <%= form_for([message.room, message]) do |f| %>
    <%= f.text_field :author %>
    <%= f.text_field :content %>
    <%= f.submit "📨 Send", class: "py-2 px-4 text-white bg-blue-500 inline-block cursor-pointer" %>
  <% end %>
<% end %>

app/views/messages/_message.html.erb
<%# locals: (message:) -%>

<%= turbo_frame_tag message, class: "group grid grid-cols-subgrid col-span-4 py-1 hover:bg-gray-50" do %>
  <time title="<%= message.created_at.iso8601 %>" class="font-extralight <%= message_color_class(message) %>">
    <%= message.created_at.strftime("%H:%M:%S") %>
  </time>

  <p class="font-bold <%= message_color_class(message) %>">
    <%= message.author %>
  </p>

  <p class="<%= message_color_class(message) %>">
    <%= message.content %>
  </p>

  <%= link_to room_message_path(message.room, message),
              class: "invisible group-hover:visible",
              data: {
                turbo_method: :delete,
                turbo_confirm: "Really delete this message?"
              } do %>
    ❌
  <% end %>
<% end %>

app/views/rooms/_form.html.erb
<%= form_with(model: room, class: "contents") do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= turbo_frame_tag :edit_title do %>
      <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <% end %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/rooms/_message_count.html.erb
<%# locals: (room:) -%>

<%= turbo_frame_tag :message_count, class: "rounded-lg px-2 py-1 text-xs bg-black text-white font-light" do %>
  <%= room.messages.count %> messages
<% end %>

app/views/rooms/_messages.html.erb
<%# locals: (room:) -%>

<%= turbo_frame_tag :message_list, class: "grid gap-x-4 message-list" do %>
  <%= render partial: "messages/message", collection: room.messages %>
<% end %>

app/views/rooms/edit.html.erb
<h1 class="font-bold text-4xl">Editing room</h1>

<%= render "form", room: @room %>

<%= link_to "Go to this room", @room, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
<%= link_to "All rooms", rooms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

app/views/rooms/index.html.erb
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
<% end %>

<div class="flex justify-between items-center mb-6">
  <h1 class="font-bold text-4xl">Rooms</h1>
  <%= link_to "New room", new_room_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
</div>

<div class="min-w-full flex flex-col gap-y-6">
  <% @rooms.each do |room| %>
    <div id="<%= dom_id room %>" class="flex justify-between items-center">
      <%= link_to "💬 " + room.title, room, class: "text-2xl rounded font-medium py-3 px-5 hover:bg-gray-100" %>
      <%= link_to "📝 Edit", edit_room_path(room), class: "rounded py-3 px-5 hover:bg-gray-100" %>
    </div>
  <% end %>
</div>

app/views/rooms/new.html.erb
<h1 class="font-bold text-4xl">New room</h1>

<%= render "form", room: @room %>

<%= link_to "Back to rooms", rooms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

app/views/rooms/show.html.erb
<%= turbo_stream_from @room %>

<div class="flex flex-col gap-y-4">
  <%= link_to "← back to all rooms", rooms_path, class: "font-light text-gray-400" %>

  <div class="flex justify-between items-center">
    <h1 class="text-4xl font-medium flex items-center gap-x-3">
      <%= form_for @room do %>
        <%= turbo_frame_tag :edit_title do %>
          <%= link_to @room.title, edit_room_path(@room) %>
        <% end %>
      <% end %>
      <%= render "rooms/message_count", room: @room %>
    </h1>

    <div class="flex gap-x-4">
      <%= link_to "📝 Edit this room", edit_room_path(@room), class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      <%= link_to "❌ Destroy this room", room_path(@room), method: :delete, class: "rounded-lg py-3 px-5 bg-red-100 font-medium" %>
    </div>
  </div>

  <%= render "rooms/messages", room: @room %>
  <%= render "messages/form", message: @room.messages.build %>
</div>